name: Checks
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run SwiftLint
        run: |
          export LINUX_SOURCEKIT_LIB_PATH=/usr/share/swift/usr/lib/
          wget -q https://github.com/realm/SwiftLint/releases/download/0.45.1/swiftlint_linux.zip
          unzip -q swiftlint_linux.zip swiftlint
          ./swiftlint lint --strict
      - name: Run Tests
        run: swift test
      

